# Generated by Django 5.0.4 on 2024-05-24 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Category Name"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "car_owner"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_category",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=100, verbose_name="Vehicle Make")),
                (
                    "model",
                    models.CharField(max_length=100, verbose_name="Vehicle Model"),
                ),
                ("year", models.CharField(max_length=50)),
                (
                    "price_per_day",
                    models.DecimalField(
                        decimal_places=2, max_digits=1000, verbose_name="Price per Day"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="default/vehicle.jpg",
                        null=True,
                        upload_to="images/vehicle/",
                    ),
                ),
                ("description", models.TextField(default="car description")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "car_owner"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Vehicle.vehiclecategory",
                    ),
                ),
            ],
        ),
    ]
