version: '3.8'

services:
  backend:
    build: .
    container_name: rideready_backend
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    ports:
      - "9000:8000"
    env_file:
      - .env

volumes:
  postgres_data:
