export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS"
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE"

export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST"
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS"
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE"

export const FETCH_ALL_CATEGORY_REQUEST = "FETCH_ALL_CATEGORY_REQUEST"
export const FETCH_ALL_CATEGORY_SUCCESS = "FETCH_ALL_CATEGORY_SUCCESS"
export const FETCH_ALL_CATEGORY_FAILURE = "FETCH_ALL_CATEGORY_FAILURE"

export const FETCH_VEHICLE_REQUEST = "FETCH_VEHICLE_REQUEST"
export const FETCH_VEHICLE_SUCCESS = "FETCH_VEHICLE_SUCCESS"
export const FETCH_VEHICLE_FAILURE = "FETCH_VEHICLE_FAILURE"

export const CREATE_VEHICLE_SUCCESS = "CREATE_VEHICLE_SUCCESS"
export const CREATE_VEHICLE_FAILURE = "CREATE_VEHICLE_FAILURE"

export const DELETE_VEHICLE_SUCCESS = "CREATE_VEHICLE_SUCCESS"
export const DELETE_VEHICLE_FAILURE = "CREATE_VEHICLE_FAILURE"

export const FETCH_ALL_VEHICLE_REQUEST = "FETCH_ALL_VEHICLE_REQUEST"
export const FETCH_ALL_VEHICLE_SUCCESS = "FETCH_ALL_VEHICLE_SUCCESS"
export const FETCH_ALL_VEHICLE_FAILURE = "FETCH_ALL_VEHICLE_FAILURE"

export const FETCH_ALL_SEE_VEHICLE_REQUEST = "FETCH_ALL_SEE_VEHICLE_REQUEST"
export const FETCH_ALL_SEE_VEHICLE_SUCCESS = "FETCH_ALL_SEE_VEHICLE_SUCCESS"
export const FETCH_ALL_SEE_VEHICLE_FAILURE = "FETCH_ALL_SEE_VEHICLE_FAILURE"

export const FETCH_ALL_BOOKED_VEHICLE_REQUEST = "FETCH_ALL_BOOKED_VEHICLE_REQUEST"
export const FETCH_ALL_BOOKED_VEHICLE_SUCCESS = "FETCH_ALL_BOOKED_VEHICLE_SUCCESS"
export const FETCH_ALL_BOOKED_VEHICLE_FAILURE = "FETCH_ALL_BOOKED_VEHICLE_FAILURE"



export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOGOUT = "AUTH_LOGOUT";



export const REMOVE_AUTH_MESSAGE = "REMOVE_AUTH_MESSAGE";