name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'terraform/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/ride-ready/backend/RideReady
          git pull origin main
          sudo docker compose down
          sudo docker compose up -d --build
          sudo docker compose exec backend python manage.py migrate
          sudo docker compose exec backend python manage.py collectstatic --noinput
